# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81478bd69fe0ee91f495ea3d8c08594a525546f249b61a81c2cbf6dfa0ec86b719dac9024cb6de87bb708c51ecad5ec179e90bb02776884f5342f8c36154be0f

test:
  secret_key_base: a9635f5a51ec912d58a11b64659a179f719b82d56e1315672ea9b8de49835cb80911c5504644fee4daa60fc9ebef3b5ab76004259ceffbf5934872dc1017781e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
